### ISSUE TITLE
Замечания к лабораторной

### ISSUE THREAD

**Issue by rredbird66** [Dariyastaa/PZRL2#1]
1. Почему в реквизитах есть .h файлы, но при этом нет .c? При таком Makefile make не будет отслеживать изменения в .c.
2. Дублирование include-ов в заголовочных файлах и файлах исходного кода.

**Comment by Dariyastaa** [comment]
Здравствуйте. Исправила.

**Comment by rredbird66** [comment]
1. В реквизитах цели main.o много лишнего. Вы разве там все эти файлы используете?
2. И что за переменная CFLAGS, которую вы используете, но нигде не определяете?

**Comment by Dariyastaa** [comment]
Исправлено.

**Comment by rredbird66** [comment]
Эхх, а кто сам исполняемый файл удалять при clean будет? Исправьте, но уже смотреть не буду сейчас. Будет на вашей совести.
Лабораторная работа 2 зачтена.
